version: '3.8'

services:
  baserow:
    image: baserow/baserow:1.35.1
    container_name: spreadsheet_consolidator_baserow
    restart: unless-stopped
    environment:
      - BASEROW_PUBLIC_URL=http://localhost:8080
      - DATABASE_URL=postgresql://baserow:baserow_password@postgres:5432/baserow
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - baserow_data:/baserow/data
    depends_on:
      - postgres
      - redis
    networks:
      - baserow_network

  postgres:
    image: postgres:13
    container_name: spreadsheet_consolidator_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=baserow
      - POSTGRES_USER=baserow
      - POSTGRES_PASSWORD=baserow_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - baserow_network

  redis:
    image: redis:7
    container_name: spreadsheet_consolidator_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - baserow_network

volumes:
  baserow_data:
    name: spreadsheet_consolidator_baserow_data
  postgres_data:
    name: spreadsheet_consolidator_postgres_data
  redis_data:
    name: spreadsheet_consolidator_redis_data

networks:
  baserow_network:
    name: spreadsheet_consolidator_network
    driver: bridge
